// blend.js — Les ordet: sounding-out / blending reading mode.
    function chooseBlendItem(){const items=WORDS.filter(w=>!w.noEmojiWord);const minBefore=Math.max(1,Math.floor(items.length/2));const queue=Array.isArray(state.blendQueue)?state.blendQueue:[];const recent=new Set(queue.slice(-minBefore));const available=shuffle(items).filter(w=>!recent.has(w.id));const picked=available[0]||shuffle(items)[0]||WORDS[0];state.blendQueue=[...queue.filter(id=>id!==picked.id),picked.id].slice(-minBefore);saveState();return picked}
    function makeBlendChoices(correctItem){const count=Math.max(1,Math.min(5,Number(state.blendDistractors)||2));const others=shuffle(WORDS.filter(w=>!w.noEmojiWord&&w.id!==correctItem.id)).slice(0,count);return shuffle([correctItem,...others]).map((item,index)=>({id:`${item.id}-${index}-${Math.random().toString(36).slice(2,7)}`,item}))}
    function clearBlendLight(){if(blendLightTimer){clearTimeout(blendLightTimer);blendLightTimer=null}if(blendGame)blendGame.litIndex=-1}
    function paintBlendLetters(){if(!els.board)return;els.board.querySelectorAll(".blend-letter").forEach((el,i)=>el.classList.toggle("lit",i===blendGame.litIndex))}
    function lightLettersSequence(pause){clearBlendLight();if(!blendGame.item)return;const n=normalizeSpellingWord(blendGame.item.word).length;const gap=Math.max(170,pause);let i=0;const step=()=>{if(!isBlendMode()||blendGame.complete){clearBlendLight();paintBlendLetters();return}if(i<n){blendGame.litIndex=i;paintBlendLetters();i++;blendLightTimer=setTimeout(step,gap)}else{blendGame.litIndex=-1;paintBlendLetters();blendLightTimer=null}};step()}
    // Sounds the letters out, getting quicker on each press. It NEVER speaks the
    // whole word — not even when pressed many times — so the app can't read the
    // word for her; merging the quick sounds into a word is her job. Speed comes
    // from a faster rate (shorter sounds) with a steady gap, which keeps the
    // speech engine responsive enough that the per-letter highlight stays in sync.
    function blendOutLoud(){if(!isBlendMode()||!blendGame.item)return;ensureAudioContext();const target=normalizeSpellingWord(blendGame.item.word);const sounds=target.split("").map(letterSoundSegment).filter(Boolean);const stage=Math.min(2,Number(blendGame.blendStage)||0);const tuning=[{rate:.5,pause:340,sub:"Hør hver lyd – én etter én."},{rate:.72,pause:280,sub:"Litt raskere nå."},{rate:.95,pause:250,sub:"Lyd dem sammen – hva blir ordet?"}][stage];setMessage("Lyd sammen",tuning.sub);clearBlendLight();const speaking=!!state.sound&&("speechSynthesis" in window);if(speaking){
      // Highlight each letter exactly when its sound starts (via the utterance's
      // onstart), and clear at the end — so the glow tracks the voice.
      const onSegmentStart=i=>{if(!isBlendMode())return;blendGame.litIndex=i;paintBlendLetters()};
      const onSegmentsDone=()=>{if(!isBlendMode())return;blendGame.litIndex=-1;paintBlendLetters()};
      speakPayload({segments:[...sounds],rate:tuning.rate,pitch:1.08,pause:tuning.pause,onSegmentStart,onSegmentsDone},false);
    }else{lightLettersSequence(420)}blendGame.blendStage=Math.min(2,stage+1)}
    function onBlendLetter(index){if(!isBlendMode()||!blendGame.item)return;ensureAudioContext();const target=normalizeSpellingWord(blendGame.item.word);const ch=target[index];if(!ch)return;clearBlendLight();blendGame.litIndex=index;paintBlendLetters();speakLetterSound(ch);blendLightTimer=setTimeout(()=>{if(blendGame.litIndex===index){blendGame.litIndex=-1;paintBlendLetters()}},760)}
    function startBlendRound(announce=false){clearBlendLight();const item=chooseBlendItem();blendGame={item,choices:makeBlendChoices(item),wrongChoiceId:null,correctChoiceId:null,complete:false,litIndex:-1,blendStage:0};cards=[];flipped=[];matched=new Set();moves=0;lock=false;els.completeOverlay.classList.remove("show");setMessage("Les ordet","Trykk hver bokstav, lyd dem sammen, og velg riktig bilde.");lastSpeechPayload={text:"Les ordet. Lyd bokstavene sammen.",rate:.82};renderBoard();updateStatus();requestAnimationFrame(ensureBoardVisible);if(announce)speakPayload({text:"Ny runde. Les ordet.",rate:.86},false)}
    function renderBlendBoard(){const{item,choices,wrongChoiceId,correctChoiceId,litIndex}=blendGame;if(!item){els.board.innerHTML="";return}const target=normalizeSpellingWord(item.word);const upper=state.uppercase!==false;const disp=upper?target:target.charAt(0)+target.slice(1).toLowerCase();const letters=disp.split("").map((ch,i)=>`<button class="blend-letter${i===litIndex?" lit":""}" type="button" data-index="${i}" data-letter="${target[i]}" aria-label="Lyd bokstaven ${ch}">${ch}</button>`).join("");const choiceButtons=choices.map(choice=>{const isWrong=choice.id===wrongChoiceId,isCorrect=choice.id===correctChoiceId;return `<button class="blend-choice${isWrong?" wrong":""}${isCorrect?" correct-reveal":""}" type="button" data-choice="${choice.id}" aria-label="Velg dette bildet"><span class="blend-choice-emoji">${choice.item.emoji}</span></button>`}).join("");els.board.style.setProperty("--cols",1);els.board.innerHTML=`<div class="blend-board"><div class="blend-clue"><div class="blend-clue-label">Les ordet</div><div class="blend-word" aria-label="${target}">${letters}</div><button class="blend-say-btn" type="button">🔊 Lyd sammen</button><div class="blend-hint">Trykk hver bokstav for å høre lyden. Trykk «Lyd sammen» for å lyde dem fortere og fortere – velg så riktig bilde.</div></div><div class="blend-choices" data-total="${choices.length}">${choiceButtons}</div></div>`;els.board.querySelectorAll(".blend-letter").forEach(btn=>btn.addEventListener("click",()=>onBlendLetter(Number(btn.dataset.index))));els.board.querySelector(".blend-say-btn")?.addEventListener("click",blendOutLoud);els.board.querySelectorAll(".blend-choice").forEach(btn=>btn.addEventListener("click",()=>onBlendChoice(btn.dataset.choice)))}
    function onBlendChoice(choiceId){if(!isBlendMode()||lock||blendGame.complete)return;ensureAudioContext();const choice=blendGame.choices.find(c=>c.id===choiceId);if(!choice)return;moves++;if(choice.item.id===blendGame.item.id){blendGame.complete=true;blendGame.correctChoiceId=choiceId;clearBlendLight();state.rounds++;state.blendStreak=(Number(state.blendStreak)||0)+1;const streak=Number(state.blendStreak)||0;saveState();const word=blendGame.item.word.toLowerCase();setMessage("Riktig!",word);playCorrectReward(3);makeConfetti(20,1300);showEmojiBurst(blendGame.item.emoji);speakPayload({segments:[`Du leste`,word],rate:.8,pitch:1.14,pause:240},false);if(streak>0&&streak%10===0){const nm=(state.childName||"").trim();setTimeout(()=>speakPayload({text:`Kjempe bra${nm?`, ${nm}`:""}`,rate:.9,pitch:1.18},false),1150)}renderBoard();updateStatus();setTimeout(()=>{if(!isBlendMode())return;startBlendRound(false)},1900)}else{blendGame.wrongChoiceId=choiceId;const prev=Number(state.blendStreak)||0;state.blendStreak=0;state.blendPraiseAt=0;state.blendSuperFired=false;saveState();setMessage("Nesten!","Lyd bokstavene sammen en gang til.");playTone(180,.12,"sawtooth",.035,0);renderBoard();updateStatus();if(prev>=5)showFlamesFalling();setTimeout(()=>{if(blendGame.wrongChoiceId===choiceId){blendGame.wrongChoiceId=null;setMessage("Les ordet","Trykk hver bokstav, lyd dem sammen, og velg riktig bilde.");renderBoard()}},800)}}
    function renderBlendDistractorButtons(){if(!els.blendDistractorButtons)return;const current=Math.max(1,Math.min(5,Number(state.blendDistractors)||2));els.blendDistractorButtons.innerHTML=[1,2,3,5].map(n=>`<button type="button" class="${n===current?"active":""}" data-dist="${n}">${n+1} bilder</button>`).join("");els.blendDistractorButtons.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{state.blendDistractors=Number(btn.dataset.dist);saveState();renderBlendDistractorButtons();if(isBlendMode())startRound(true)}))}
