// feedback.js — WebAudio reward sounds, streak fanfares and flame effects.
    let audioCtx=null;
    function ensureAudioContext(){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}catch{return null}}
    function playTone(freq=.0,duration=.12,type="sine",volume=.06,start=0){const ctx=ensureAudioContext();if(!ctx)return;const now=ctx.currentTime+start;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);gain.gain.setValueAtTime(0.0001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.01);gain.gain.exponentialRampToValueAtTime(0.0001,now+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+duration+.03)}
    function playClapBurst(start=0){const ctx=ensureAudioContext();if(!ctx)return;const pulseOffsets=[0,.03,.065];const gains=[.09,.07,.055];pulseOffsets.forEach((offset,index)=>{const now=ctx.currentTime+start+offset;const buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate*.09),ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;const shaped=(1-t)*(1-t);data[i]=(Math.random()*2-1)*shaped}const source=ctx.createBufferSource();source.buffer=buffer;const high=ctx.createBiquadFilter();high.type="highpass";high.frequency.setValueAtTime(900,now);const band=ctx.createBiquadFilter();band.type="bandpass";band.frequency.setValueAtTime(2100-(index*180),now);band.Q.value=.75;const gain=ctx.createGain();gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(gains[index],now+.004);gain.gain.exponentialRampToValueAtTime(.0001,now+.07);source.connect(high);high.connect(band);band.connect(gain);gain.connect(ctx.destination);source.start(now);const click=ctx.createOscillator();const clickGain=ctx.createGain();click.type="triangle";click.frequency.setValueAtTime(1200-(index*120),now);clickGain.gain.setValueAtTime(.0001,now);clickGain.gain.exponentialRampToValueAtTime(.012,now+.003);clickGain.gain.exponentialRampToValueAtTime(.0001,now+.03);click.connect(clickGain);clickGain.connect(ctx.destination);click.start(now);click.stop(now+.04)})}
    function playCorrectReward(level=1){const safeLevel=Math.max(1,Math.min(8,level));const base=430+safeLevel*38;playTone(base,.06,"triangle",.055,0);playTone(base*1.12,.07,"triangle",.045,.06);playTone(base*1.33,.1,"sine",.05,.13);playTone(base*1.5,.14,"sine",.038,.23);if(safeLevel>=4)playTone(base*2,.11,"triangle",.022,.33);playClapBurst(.04)}
    function playSpellingSuccessReward(streak=1){const level=Math.max(1,Math.min(12,Number(streak)||1));const root=330*Math.pow(2,(level-1)/12);const steps=[0,4,7,11,14,16,19];const noteCount=Math.min(steps.length,3+Math.floor((level-1)/2));for(let i=0;i<noteCount;i++){const t=i*.07,freq=root*Math.pow(2,steps[i]/12);playTone(freq,.13,i<noteCount-1?"triangle":"sine",.052,t);if(level>=4)playTone(freq/2,.12,"sine",.02,t)}const finale=root*Math.pow(2,steps[noteCount-1]/12)*2;playTone(finale,.24,"sine",.04,noteCount*.07);if(level>=6)playTone(finale*Math.pow(2,4/12),.22,"sine",.022,noteCount*.07+.04);playClapBurst(.05)}
    function playStreakLostSound(){ensureAudioContext();const freqs=[392,330,262,220,165];freqs.forEach((freq,i)=>{playTone(freq,.26,"sawtooth",.06,i*.2);playTone(freq*.5,.24,"sine",.028,i*.2+.06)})}
    function showFlamesFalling(){if(!els.movesPill)return;const rect=els.movesPill.getBoundingClientRect();const cx=rect.left+rect.width/2;const cy=rect.top+rect.height/2;for(let i=0;i<5;i++){const el=document.createElement("span");el.textContent="🔥";el.className="flame-falling";const drift=(Math.random()-.5)*160;const rot=(Math.random()-.5)*420;const delay=i*.07;el.style.cssText=`left:${cx+(Math.random()-.5)*rect.width*.7}px;top:${cy}px;--drift:${drift}px;--rot:${rot}deg;animation-delay:${delay}s`;document.body.appendChild(el);setTimeout(()=>el.remove(),2000)}playStreakLostSound()}
    function showFlamesRising(el){const target=el||els.movesPill;if(!target||prefersReducedMotion())return;const rect=target.getBoundingClientRect();const cx=rect.left+rect.width/2;const cy=rect.top+rect.height/2;for(let i=0;i<16;i++){const flame=document.createElement("span");flame.textContent="🔥";flame.className="flame-rising";const drift=(Math.random()-.5)*240;const rot=(Math.random()-.5)*360;const delay=Math.random()*.32;flame.style.cssText=`left:${cx+(Math.random()-.5)*Math.max(rect.width,80)}px;top:${cy}px;--drift:${drift}px;--rot:${rot}deg;animation-delay:${delay}s`;document.body.appendChild(flame);setTimeout(()=>flame.remove(),1900)}}
    function playStreakFanfare(){ensureAudioContext();const notes=[392,523.25,659.25,783.99,1046.5];const starts=[0,.12,.24,.36,.52];const durations=[.13,.13,.13,.18,.5];notes.forEach((note,i)=>{playTone(note,durations[i],i<4?"triangle":"sine",.06,starts[i]);playTone(note/2,durations[i]+.04,"sine",.024,starts[i]);if(i>=3)playTone(note*1.5,durations[i],"sine",.02,starts[i])});playClapBurst(.04);playClapBurst(.3);playClapBurst(.58)}
    function celebrateStreak(streak,el,source){const s=Number(streak)||0;if(s<5)return;ensureAudioContext();playStreakFanfare();showFlamesRising(el);makeConfetti(42,1700);if(source){const key=source+"PraiseAt";const last=Number(state[key])||0;if(s>=last+5){state[key]=s;saveState();const name=(state.childName||"").trim();setTimeout(()=>speakPayload({text:`Du er kjempe flink${name?` ${name}`:""}`,rate:.9,pitch:1.16},false),650)}}}
    // Easter egg: one huge full-screen fire eruption, fired once when the fire
    // pill is pressed at a streak of 10. A double fanfare, lots of confetti and
    // a screen-filling shower of big rising flames.
    function showSuperFire(){ensureAudioContext();playStreakFanfare();setTimeout(playStreakFanfare,560);makeConfetti(90,2800);if(!prefersReducedMotion()){for(let i=0;i<90;i++){const flame=document.createElement("span");flame.textContent="🔥";flame.className="flame-rising";const x=Math.random()*window.innerWidth;const drift=(Math.random()-.5)*340;const rot=(Math.random()-.5)*460;const delay=Math.random()*.7;const size=Math.round(40+Math.random()*72);flame.style.cssText=`left:${x}px;top:${window.innerHeight*0.92}px;font-size:${size}px;--drift:${drift}px;--rot:${rot}deg;animation-delay:${delay}s`;document.body.appendChild(flame);setTimeout(()=>flame.remove(),2600)}}const name=(state.childName||"").trim();setTimeout(()=>speakPayload({text:`Ti på rad! Du er en lesehelt${name?`, ${name}`:""}!`,rate:.92,pitch:1.18},false),420)}
    function resetSpellingStreak(){const prev=Number(state.spellingStreak)||0;state.spellingStreak=0;state.spellingPraiseAt=0;saveState();updateStatus();if(prev>=5)showFlamesFalling()}
    function addSpellingStreak(){state.spellingStreak=(Number(state.spellingStreak)||0)+1;state.spellingBestStreak=Math.max(Number(state.spellingBestStreak)||0,state.spellingStreak);saveState();return state.spellingStreak}
    function playRoundCompleteJingle(){const notes=[523.25,659.25,783.99,1046.5,783.99,1046.5];const starts=[0,.09,.18,.31,.48,.62];const durations=[.08,.08,.1,.18,.12,.24];notes.forEach((note,i)=>{playTone(note,durations[i],i<3?"triangle":"sine",i<3?.05:.04,starts[i]);if(i>=3)playTone(note/2,durations[i]+.02,"triangle",.018,starts[i])});playClapBurst(.08);playClapBurst(.28);playClapBurst(.54)}
