// state.js — persistent state load/save + live runtime game state + DOM refs.
    function readStoredState(key){try{const raw=localStorage.getItem(key);if(!raw)return null;const parsed=JSON.parse(raw);return parsed&&typeof parsed==="object"?parsed:null}catch{return null}}
    function findLegacyState(){let best=null,bestVersion=-1;try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key||key===storageKey)continue;const m=key.match(legacyStateKeyRe);if(!m)continue;const version=Number(m[1]);if(version>bestVersion){const data=readStoredState(key);if(data){best=data;bestVersion=version}}}}catch{}return best}
    function loadState(){const current=readStoredState(storageKey);if(current)return{...defaultState,...current};const legacy=findLegacyState();if(legacy)return{...defaultState,...legacy};isFirstBoot=true;return{...defaultState}}
    function saveState(){try{localStorage.setItem(storageKey,JSON.stringify(state))}catch{}}
    function prefersReducedMotion(){return !!(window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)}
    let isFirstBoot=false;
    let state=loadState(),cards=[],flipped=[],matched=new Set(),moves=0,lock=false,lastSpeechPayload={text:"Finn to som hører sammen."};
    let spellingGame={target:"SOL",emoji:null,showWord:true,choices:[],filled:[],wrongChoiceId:null,complete:false},spellingHintTimer=null,spellingHintActive=false;
    let emojiWordGame={item:null,choices:[],wrongChoiceId:null,correctChoiceId:null,complete:false};
    let blendGame={item:null,choices:[],wrongChoiceId:null,correctChoiceId:null,complete:false,litIndex:-1,blendStage:0},blendLightTimer=null;
    const els={modeGrid:document.getElementById("modeGrid"),pairButtons:document.getElementById("pairButtons"),pairSettings:document.getElementById("pairSettings"),spellingDifficultyField:document.getElementById("spellingDifficultyField"),spellingDifficultyButtons:document.getElementById("spellingDifficultyButtons"),emojiWordDistractorField:document.getElementById("emojiWordDistractorField"),emojiWordDistractorButtons:document.getElementById("emojiWordDistractorButtons"),blendDistractorField:document.getElementById("blendDistractorField"),blendDistractorButtons:document.getElementById("blendDistractorButtons"),board:document.getElementById("board"),message:document.getElementById("message"),movesPill:document.getElementById("movesPill"),foundPill:document.getElementById("foundPill"),roundsPill:document.getElementById("roundsPill"),streakPill:document.getElementById("streakPill"),soundToggle:document.getElementById("soundToggle"),easyModeToggle:document.getElementById("easyModeToggle"),uppercaseToggle:document.getElementById("uppercaseToggle"),nextRoundBtn:document.getElementById("nextRoundBtn"),speakBtn:document.getElementById("speakBtn"),completeOverlay:document.getElementById("completeOverlay"),completeText:document.getElementById("completeText"),confetti:document.getElementById("confetti"),emojiBurst:document.getElementById("emojiBurst"),adultBtn:document.getElementById("adultBtn"),adultPanel:document.getElementById("adultPanel"),wordList:document.getElementById("wordList"),storedSpellWordList:document.getElementById("storedSpellWordList"),childNameInput:document.getElementById("childNameInput"),spellingWordInput:document.getElementById("spellingWordInput"),useSpellingWordBtn:document.getElementById("useSpellingWordBtn"),randomSpellingWordBtn:document.getElementById("randomSpellingWordBtn"),resetProgressBtn:document.getElementById("resetProgressBtn"),fullscreenBtn:document.getElementById("fullscreenBtn"),nameDialog:document.getElementById("nameDialog"),nameDialogInput:document.getElementById("nameDialogInput"),nameDialogSave:document.getElementById("nameDialogSave"),nameDialogSkip:document.getElementById("nameDialogSkip"),gateDialog:document.getElementById("gateDialog"),gateCard:document.getElementById("gateCard"),gateQuestion:document.getElementById("gateQuestion"),gateOptions:document.getElementById("gateOptions"),gateCancel:document.getElementById("gateCancel"),ttsHint:document.getElementById("ttsHint")};
    function modeInfo(){return MODES.find(m=>m.id===state.mode)||MODES[1]}
    function isSpellingMode(){return state.mode==="spell"||state.mode==="emojiSpell"}
    function isEmojiWordMode(){return state.mode==="emojiWord"}
    function isBlendMode(){return state.mode==="blend"}
